version: '3'
services:
    portfolio_optimization:
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: portfolio_optimization
        volumes:
            - "./:/app"